language: node_js
node_js:
- node
install:
- npm install -g travis-ci-cloudfront-invalidation
- npm install
cache:
  directories:
  - node_modules
notifications:
  email: false
git:
  depth: false
before_deploy:
- npm run prod
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$AWS_BUCKET_NAME"
  local-dir: dist
  region: eu-west-2
  skip_cleanup: true
  acl: public_read
  on:
    repo: jamtartley/pathfinding
    branch: master
after_deploy:
- travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $AWS_CLOUDFRONT_DIST_ID
  -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
env:
  global:
  - secure: ItAojlfKzBuzqBW0lS9IfVv0cmPaoKG4EpfCQUb7d8VabLwQWN4uaiAb3fnu2uNQA4SZMZ203/qh+PHsP0RggwgXQYWxnFZKFQ24jeBb1QFHi1KP+3BCzxch9fD+8uPl8jCr27j0Yxalf9hodsbrfiJILqsormHMitq6UEs881p0NCZkUo5zG4OQuUNpicD39g8upn0XQrtYbG38NPPtrUUFBHrNTDwy9MuDKw8jaznS8/yn4rLkXEOUz+DIqduUZAmQzmoCaDrzywuZa4GnS7uWMsSx2usdSciwPEQQUoM0ZJNdjhBceJBmtg8xm+ix0fYNhC6Tz2WvZKYDu3JtdJ2AhgC1QasjDqvxfehajbv6Su9IcOREmC9Bmk403P9pksMGaL163XSBd/zL3WVzbVwO5ODeVwFezegU2Z4YtlWI75UsvdF/G56lsHLVy9Ov4zn9sbUK+GABTcRC4SMW57HI4tvgObSgt0mXTTtiotHS71WQsrk8Kjqw85IPb/nhoi+wIQAYrkvQEvQHRoVcLLG13ooUKc8hq8T5nlLEyMh7I1RzpWLbiBdtN+rYotuzEK8TYKatafx23qLV64VuHljF0s2sTu5QR6uVf/zOXJwkU6zb8myWs/HWS13XzRnwnfL5qeqvWou40XVJcIyW6EG+nu27pnSShO8JgX817A4=
  - secure: Z95YxlvC/wBvRtGE8agihhQEug5Z/gOEn4AzyFgkPi8bLc2hVwJYr4wp3jDWMz4d/uXd/y7prwz0HGCI4pZfH5+MGr8xfmwrhVEoV9XLbkvoNJ2hAcYna0bX/6dY8fWpumGEQTUfdB23MNaHASpJwR4btcBaliLN1evXcbETXm6hfBL3gOhb7BXsbmrc1jFIC8tQdO1IoJ3GTgGHJyRx82tPcgzL+2yBAlNMCx2f4cPFb4l/s+5cueQBNemgd1dlGyKhAl+Sd4TIZSg0KSyJeIHbo/+HroijxWUk9jHS6MzUMyXQmB2mFRov+t2loGFaUSpqSAuKRVvxJ6VrLB0NEJ68+oS1QwGvUjM3t1qEdwOxkcMRHpt0hkEcbkp8EzSbdReWQk1rRelAUCQ9MrM8954u0UjXRsaGbqbUmU97mSYcSq1+agVl9pXtSviPhV17pSNmkwBuNBbtK4tiSdk+9Je4Ku7f8LlKx6eOf+QRvWd2zPc/coGipBHl96atbjq7HxjBNYX8P9MycujJH99Nh+LMQH54n9llE9jYImxx8j0l25qnFCcwQsC1GVXpY+khwy85ejpur/+uGLvbhh/miplm/9JmDauLw97oydJoe9MJc/9W3T9lY69jzER12yaL4ZvH6PsUeQTrOZTaav6hn24uHvPugW5ppRnaaK7kZok=
  - secure: ZJr9fJuhbCWS3whgYD4qUhuCpgP7Zpfv69LK3DAFiEf18CBFs7W8F/8OQSxRZ5WWjk1hCVn38LZBDqlmvblHUzrW8W4mek7FgQUBgnBv/WY72DogxnBcrCchS/w4nr3gq3Pe4eLg0Cml8WdE9pDYOB1+eu82mB+AwVR8ugHaOz2jRf5c10V3dfyjPRqlm9fYvToRsshmat/inuonOKMB7Kin2oO4iaigQkr9C+tv7Wmm/qs7W17qhFH22jhpBoBTaZbgVihfV2jhn6+babP1v5dSUDzfd+pMhDJPUGilED1FkrCRd2P+NwrDv7VvOmlXcusljhX2ju8+SfQF1mok6ztfv7rp4n1CNdJm6ZyAqinLwdjj6u6McGZMyW+sT4uQPqj97wytzSLqBPjkxLME0hSZDBlSOYU1o3f4oLW5AgpFpniKPaHR4Z3EVXUQZmw9tcViCE+aK4zKrfGyGr2YxZnW8wsB1TBH1qqCY5i9gEvRLUmgPEYM3EPG+1ulpewgfai0PtlxQzPq9jA4fZt7rroSSEV2ZWSPJJUFfxHhl2ooWZTCCgsQV2sLCx79pYBbbAGB/dBWIP48dHDR1yQhF7/7sLHu2DfDQA7lhs2d9+4OylzPN3nZHhWgQFiKI2uMInMzfcyU4vZmABPgqpJfbdUGIL7nczt5euXpxNRmv+Y=
  - secure: o9M1G/0jP0+ON1G+HSH0Q2pJMLGQSklcooDcUipvGtPJ4x3YqC/oxjJRXYSh7UTLMkjR6cVyVYLlRFg45QLhuLqLCnzVXS2V4M3Ggc8SduMAlz0KXxw792M3U0B2Hx9BlX+H8aXKA5oBuYorPwgzHTUcssKIGebYybyuBvN182FthpK6U175Dm0EoVGunfg6Obz0RLbeRtlJPzBngSKvgWj1hTMEbAWVllNsYv1UBhprpgrPRW17CkDmy60SXsqgPchrJ4TZI9wGHrGauq7mh8IsdZCIPiuWAa9keMoYjQ8mTfnGkIVJjRWQSnq4uRgRrLClQ+WCg5/dV4l248ZURSbd4ip7Adx+J3MwnHOdtUwpo6rTDEtmze6sCL8x5gsSlUmn2W7P+Qa9Kvw9wZIIQExRYiVvnumZ4trvzof5MMOyU1lCLSHYuntNV0UUeDGJ2PCqE9sGoo4biFqtHkJuhpVmVoQGOjYwKSg7eJJnZOttyQQfrwjHgABPMutFlEah19lLg43x71aJ2xt4U+KtD2fX55LdPBjmnUFnnnxp6UdwrmSDNzbKE4DmjMgolDgrXU0WROdCwZjkjOkVodzhxRJg/2ex6u+BQCi1IQ57txe1Ej0cP++crSVoVfMBf8JaCL1MO8AVrypy/tgyFPUZBzCEsVdd6k5LExmj0a/mV8o=
